name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3
